version: '3.8'

services:
  tx_processor:
    build: .
    container_name: tx_processor_service
    environment:
      - RPC_URL
      - RPC_RETRY
      - RPC_TIMEOUT
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - REDIS_PASSWORD
      - REDIS_SSL
      - REDIS_CLUSTER
      - REDIS_MAX_BLOCKS
      - REDIS_TTL_SECONDS
      - LOG_DEBUG
      - LOG_TO_FILES
      - LOG_LEVEL
      - PROCESSOR_QUEUE_KEY
      - PROCESSOR_BLOCK_TIMEOUT
      - TEST_MODE=${TEST_MODE:-false}  # Add test mode env var for consistency
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis_tx
    restart: unless-stopped

  redis_tx:
    image: redis:7-alpine
    container_name: redis_txprocessor
    command: >
      sh -c "redis-server --requirepass \"$${REDIS_PASSWORD?No Redis Password Set}\""
    ports:
      - "${REDIS_PORT:-6379}:6379"
    profiles:
      - local
      - test  # Add test profile
    restart: unless-stopped