version: '3.8'

services:
  tx_processor:
    build: .
    container_name: tx_processor_service
    environment:
      - RPC_URL
      - RPC_RETRY
      - RPC_TIMEOUT
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - REDIS_PASSWORD
      - REDIS_SSL
      - REDIS_CLUSTER
      - REDIS_MAX_BLOCKS
      - REDIS_TTL_SECONDS
      - LOG_DEBUG
      - LOG_TO_FILES
      - LOG_LEVEL
      - PROCESSOR_QUEUE_KEY
      - PROCESSOR_BLOCK_TIMEOUT
      - TEST_MODE=${TEST_MODE:-false}  # Add test mode env var for consistency
    env_file:
      - .env
    volumes:
      - ${CONFIG_PATH:-./config}:/app/shared_config:ro
      - ${COMPUTES_PATH:-./computes}:/app/computes:ro
      - ./logs:/app/logs
    depends_on:
      - redis_tx
    restart: unless-stopped

  redis_tx:
    image: redis:7-alpine
    container_name: redis_txprocessor
    command: >
      sh -c "redis-server --port ${REDIS_PORT:-6379} --requirepass \"$${REDIS_PASSWORD?No Redis Password Set}\""
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -h ${REDIS_HOST:-localhost} -p ${REDIS_PORT:-6379} ping | grep -q PONG && ! redis-cli -h ${REDIS_HOST:-localhost} -p ${REDIS_PORT:-6379} info persistence | grep -q 'loading:1'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    volumes:
      - ./redis_data:/data
    # Add optional password and memory configurations
    environment:
      - REDIS_PASSWORD
      - REDIS_HOST
    profiles:
      - local
      - test

  rate-limiter:
    image: ${RATE_LIMITER_IMAGE:-ghcr.io/powerloom/rate-limiter:dockerify}
    environment:
      - DEFAULT_RATE_LIMIT=${DEFAULT_RATE_LIMIT:-1000}
    command: poetry run uvicorn app:app --host 0.0.0.0 --port ${RATE_LIMITER_PORT:-8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${RATE_LIMITER_PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - local
      - test
    env_file:
      - .env