name: Build and Push to ECR

on:
  push:
    branches:
      - gh-actions-ecr-push  # Only on this branch for now

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build-and-push:
    name: Build and Push Docker Image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::402604160093:role/github-action-role
          aws-region: us-east-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Verify identity
        run: aws sts get-caller-identity

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 402604160093.dkr.ecr.us-east-2.amazonaws.com
          ECR_REPOSITORY: snapshotter-periphery-txprocessor
          IMAGE_TAG: latest
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA \
            .
